### ISSUE TITLE
 What does a perfect day look like to you?

### ISSUE THREAD

**Issue by arthurvr** [MoOx/ama#1]

**Comment by MoOx** [comment]
I think perfection does not exist. That said, here would be the kind of day I will really enjoy:
- Wake up early (around 5/6am), because I like the silence of the night and the calm of morning. It helps me to handle my todo list, check my calendar, sort my mailbox to prepare my day.
- When the sun is here, I really like to have a breakfast with my wife. I love her so much... If I don't start the day with her, I will probably have a really bad day.
- After this, we will enjoy the [view of our beautiful garden](https://instagram.com/dame.bio/) and the life there is in it. We try to create an awesome ecosystem with a lots small animals (birds, bees, bugs...).
- Then I might enjoy a physical activity (tinkering, gardening...) or some more intellectual work (coding for fun or to pay bills - or both at the same time!). 
- I love to eat good things, so I will take the time to prepare a meal for/with my wife.
- After the lunch, I will take around half an hour to read a book/comic or to play a (video?) game with my wife.
- Now it's time for serious things here is the things I would love to do in an afternoon:
  - Do some extreme sport (skydive, skate, paintball with friends...)
  - Build something with my hands, I like DIY things.
  - Some code! I like to handle things via random works. I need sometimes to work for other people to pay my bills ^^.
- Then... "Aperitif!" with my wife, and/or with some friends. I love this kind of moment.
- Obviously, it will be time for diner, with some wine.
- Again, after diner, a little session reading/coding is appreciated.

The part of the day I hate the most is when my eyes start to tell me that I should sleep. I don't like to sleep because I can't do "things". Before sleeping, I will make a huge hug to my wife. Because hugs are awesome and good for health.

Most of the things I said before are actually happening (even if I don't skydive every afternoon), and I feel very lucky about that. I love my life how it is. At home with my wife most of the day ♥️.
