### ISSUE TITLE
How much time do you spend on your freelance work vs. your open source work?

### ISSUE THREAD

**Issue by mxstbr** [MoOx/ama#12]
And how do you balance it?

**Comment by MoOx** [comment]
I am pretty dumb with this sort of thing. Or very strict, as you like :)
- freelance work: 7h per day (8am to 12am + 1pm to 4pm) during missions
- open source: depend on my "free" time but can be at max 6h per day: 5am to 8am + 8pm to 11pm), but in reality, it's more 2 or 3h per day.
- between 4pm and 8pm, I usually build and maintain stuff, but not using a computer (see below)

I am almost doing full time missions all the time and take very few vacations (maybe because I love what I do). But when I take some, or when I have no mission, I barely use my computer. Just my smartphone to still keep my knowledge "up to date" (or at least my unknown knowledge: I like to know the things I don't know).

Note that sometime I work on open source stuff during my freelance work, as soon as it's relevant for my current mission :)

About health: that's a lot of computer time per day, but take this in consideration:
- I barely use my computer the weekend
- I work on [a convertible desk](https://twitter.com/search?q=standing%20from%3AMoOx&src=typd) (so I work several hours per day standing on my [level (fluidstance)](http://www.fluidstance.com/product/))
- I move a lot when I am not in front of my computer (gardening, handy work, DIY stuff etc)

**Comment by mxstbr** [comment]
Oh wow, that is a lot more planned through than my day! Thanks for the answer!

As a followup question, do you find yourself sticking to that schedule religiously, or do you often work longer/shorter than planned?

**Comment by MoOx** [comment]
For my freelance work, I am sticking to the time my client are paying for. They pay for my time, not results. Sometimes I often work 20min more, since sometimes I handle some mails, github responses, etc.

For open source, it just depends on "do I want to code or do I want to enjoy something else" (with my wife). For example I only code the evening when my wife reads books :D Otherwise I enjoy life with her.
