### ISSUE TITLE
What's your favourite search engine and why?

### ISSUE THREAD

**Issue by gristel** [MoOx/ama#16]

**Comment by MoOx** [comment]
Currently I am using DuckDuckGo most of the time for multiple reasons:
- it's a search engine that doesn't track you.
- it has a lot of nice shortcut for certain queries (see https://twitter.com/search?q=duckduckgo%20from%3AMoOx&src=typd)
- !bang are definitely a killer feature.

To be honest, I sometimes use !g (google) for certains queries, but you already know that I try to avoid all Google services (because I don't like companies that makes money on your personal data).

**Comment by MoOx** [comment]
I just saw that black-screen is now on brew. I will try it and we will see :)

```console
$ brew cask install black-screen
```
