### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [MoOx/ama#3]

**Comment by MoOx** [comment]
When I was 10 yo, we get at home our first computer. Most games at this time need to be launch from MS-Dos, in CLI. That's how your become comfortable with a computer.
At 14 yo, I was doing my first website (with Dreamweaver) for the game series "The Legend Of Zelda" that would includes a lot of walkthroughs and tricks. At this time my internet connection was 56kb/s. Hard to to upload a 30MB website (that was the size of my entire website, yeah). I planned to upload it from an internet café but I never had the chance to do so: my hard disk died, and months of work with it. That's how you learn to do some backups and to automate them.
During high school, when mathematics teachers ask you to buy an awesome calculator (TI-82) there is 2 things you do with it: add some cheat-sheets in it and get games. And when in the schoolroom everyone have the same game and everyone is trying to do the best score, measures must be taken. That's how I learned how to "hack" a game (I open the code, learn some basics stuff, found the variable where was stored the score, then I understand how the buttons where working in order to add a simple button: each time you press on it, your score was x2. This way, it was easy to do the best score).
After that I add to choice after high school: learn how to become a great actor (I was doing some theater and loved this) or learn how to be a computer hacker (programmer) because computer were fun and I like to do things with them. My parents were not in favor of the job "that is not a job" (being an actor). So I start to learn programming the "right way" (OOP haha) and here am I.
