### ISSUE TITLE
How did you join your first GitHub Organization?

### ISSUE THREAD

**Issue by claudiopro** [MoOx/ama#6]

**Comment by MoOx** [comment]
Can't really remember if I created one (maybe css-recipes) or if I joined something like Boxen (when I were using this overkill app (for me)).
Anyway I think what matters is more "why did you start contributing to a open source project" and the answer is "because there were a bug and I want it to be fixed asap".

I love to say "if you want something done right, do it yourself" :)

**Comment by claudiopro** [comment]
That's a very insightful answer, thanks!
