### ISSUE TITLE
How do you manage your sleep?

### ISSUE THREAD

**Issue by clementgalidie** [MoOx/ama#7]
Hello!
Long nights? Short nights? Polyphasic sleep? Do you have a kind of 'pattern' like going to bed around the same hour each day?

**Comment by MoOx** [comment]
If I were alone (no wife) I would go for polyphasic sleep (OPTIMIZING ALL THE THINGS) but you know, we live in a society with others people.
So I follow a simple pattern: I go to bed around 9pm, read books/comics/watch a movie/code shit then sleep around 10/11/12pm. I woke up around 5:30 but sometimes I can stay to bed for 2 hours or 3 depending on the intensity of the physical activity I did the day before.
Same pattern each day. There is no "weekend" for me (and I don't want to need "a weekend" because "the work week was long", but that's another topic).
