### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [MoOx/ama#8]

**Comment by MoOx** [comment]
I used to be a teacher in my previous school to teach basic programming lesson about C, HTML/CSS/JS but it take too much time since that was in addition to open source and my job as a freelance.

I am sharing my experience and knowledge via a french website putaindecode.fr (which will become putaindecode.io soon, with content in english). See #10 for the explanation of the name.
That takes me a considerable amount of time in addition to the open source projects I am involved in, so beside that I am not really taking time for other peoples.

That said, I am often available on a chat to help on Discord [reactiflux](http://join.reactiflux.com/) and [putaindecode](https://discordapp.com/invite/0ZotIeLBQxq2z713) servers.
